### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ahmed-bashir-ms** [Yadentra/Test-Automation-Homework#1]
**This is a Feedback, you can close the issue after incorporating the feedback.**

- Scripts are fine. 

- In the session we use `time.sleep(seconds)` for demonstration purpose. However, it should be avoided and `expected_conditions` should be use. For this homework, it is fine.

- In `task3.py`, where you have automated the login process of **LinkedIn**, please remove your own email address and password, replace it with a dummy one.

**Comment by Yadentra** [comment]
Understood. Thank you
